# This an example input file for ARetirementPlanner.py

# The format of this file will likely change in the future as
# the program changes in the future.

# most fields are options and have resonable defaults

#retirement_type = 'joint' # could be single, joint (married), ??? TODO

returns = 6		# return rate of investments
inflation = 2.5	# yearly inflation rate

# what to optimize for? 'Spending' or spending 'PlusEstate'
#maximize = "PlusEstate"


[iam.spouse]
primary = false
age = 54
retire = 60
through = 75 # needs documenting: assumes on death all accounts go to survivor

[iam.will] # iam (for each) is required in some joint cases (".xxx" use to match accounts IRA/roth)
primary = true
age = 56
retire = 58
through = 72

[SocialSecurity.will]
amount =  31000  # $31,000 at Full Retirement Age (FRA); Assumes inflation, 85% taxed
FRA = 67
age = "68-"

[SocialSecurity.spouse]
amount = 21000  # -1 for default spouse amount, amount at Full Retirement Age (FRA); Assumes inflation, 85% taxed
FRA = 67
age = "70-"

[income.mytaxfree]
amount = 3000
age = "56-"
inflation = false
tax = false          # count this as ordinary taxable income (true/false)

[income.rental_1]
amount = 36000
age = "67-"
inflation = true
tax = true          # count this as income tax

[income.rental_2]
amount = 2400
age = "67-"
inflation = true
tax = true          # count this as income tax

#[desired.income]
#amount = 45000    # want $120,000 per year
#age = "68-"
#inflation = true
#tax = true          # count this as income tax

#[max.income]
#amount = 150000
#age = "68-"
#inflation = true
#tax = false 

## extra payments required (here mortgage at $750/mo for 12 years)
#[expense.mortgage]
#amount = 3800
#age = "56-57"

# after tax savings accounts
[aftertax]
bal =   700_000
basis = 400_000		# for capital gains tax
contrib = 10        # specify the amount you will contribute anually for the specified period
#inflation = true   # will you increase the contribution to match inflation?
period = '56-65'

# pre-tax IRA accounts
[IRA.will]
#[IRA]
bal = 2_000_000
#rate = 7.25
contrib = 100
inflation = true   # will you increase the contribution to match inflation?
period = '56-65'

[IRA.spouse]
bal = 200_000

# roth IRA accounts
[roth.spouse]
bal = 100_000
contrib = 000